name: Yarn CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
